### ISSUE TITLE
[Question] Conditional Probabilities for last names in L2 voter file too small

### ISSUE THREAD

**Issue by shu3hamiitkgp** [kosukeimai/wru-data#1]
Hi @kosukeimai ,
First of all thanks for sharing this data, and making it public. I wanted to understand why the values for P(last name|ethnicity) are so low (in the order of e-8) for most surnames in the larger data provided by L2. Is there a count level data also available for these surnames to validate, also if there are any normalization steps done on the data please let me know?

**Comment by kosukeimai** [comment]
These conditional probabilities are expected to be small.  Please see [our Scientific Data paper](https://imai.fas.harvard.edu/research/names.html) for more details.
